// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ZDrive.FileService.Infrastructure.Persistence;

#nullable disable

namespace ZDrive.FileService.Infrastructure.Migrations
{
    [DbContext(typeof(FileDbContext))]
    partial class FileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.FileNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("blob_path");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_folder");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manifest_hash");

                    b.Property<string>("MimeType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<NpgsqlTsVector>("name_tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("name_tsv")
                        .HasComputedColumnSql("to_tsvector('simple', name)", true);

                    b.HasKey("Id")
                        .HasName("pk_file_nodes");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_file_nodes_is_deleted");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_file_nodes_parent_id");

                    b.HasIndex("name_tsv")
                        .HasDatabaseName("ix_file_nodes_name_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("name_tsv"), "GIN");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_file_nodes_tenant_id_user_id");

                    b.HasIndex("TenantId", "UserId", "ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_file_nodes_tenant_id_user_id_parent_id_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("file_nodes", "files");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobVersionId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_version_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manifest_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_file_versions");

                    b.HasIndex("FileId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_file_versions_file_id_version_number");

                    b.ToTable("file_versions", "files");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("link_token");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("permission");

                    b.Property<Guid>("SharedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_by");

                    b.Property<Guid?>("SharedWith")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_with");

                    b.HasKey("Id")
                        .HasName("pk_shares");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_shares_file_id");

                    b.HasIndex("LinkToken")
                        .IsUnique()
                        .HasDatabaseName("ix_shares_link_token");

                    b.ToTable("shares", "files");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.FileNode", b =>
                {
                    b.HasOne("ZDrive.FileService.Domain.Entities.FileNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_nodes_file_nodes_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.FileVersion", b =>
                {
                    b.HasOne("ZDrive.FileService.Domain.Entities.FileNode", "File")
                        .WithMany("Versions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_versions_file_nodes_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.Share", b =>
                {
                    b.HasOne("ZDrive.FileService.Domain.Entities.FileNode", "File")
                        .WithMany("Shares")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shares_file_nodes_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ZDrive.FileService.Domain.Entities.FileNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Shares");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
