<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZDrive.AuthService.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZDrive.AuthService.Application\ZDrive.AuthService.Application.csproj" />
    <ProjectReference Include="..\ZDrive.AuthService.Infrastructure\ZDrive.AuthService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\ZDrive.Shared\ZDrive.Shared.csproj" />
  </ItemGroup>

</Project>
