<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZDrive.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AuthService\ZDrive.AuthService.Application\ZDrive.AuthService.Application.csproj" />
    <ProjectReference Include="..\AuthService\ZDrive.AuthService.Infrastructure\ZDrive.AuthService.Infrastructure.csproj" />
    <ProjectReference Include="..\FileService\ZDrive.FileService.Application\ZDrive.FileService.Application.csproj" />
    <ProjectReference Include="..\FileService\ZDrive.FileService.Infrastructure\ZDrive.FileService.Infrastructure.csproj" />
    <ProjectReference Include="..\StorageService\ZDrive.StorageService.Application\ZDrive.StorageService.Application.csproj" />
    <ProjectReference Include="..\StorageService\ZDrive.StorageService.Infrastructure\ZDrive.StorageService.Infrastructure.csproj" />
    <ProjectReference Include="..\SyncService\ZDrive.SyncService.Application\ZDrive.SyncService.Application.csproj" />
    <ProjectReference Include="..\SyncService\ZDrive.SyncService.Infrastructure\ZDrive.SyncService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\shared\ZDrive.Shared\ZDrive.Shared.csproj" />
  </ItemGroup>
</Project>
